### ISSUE TITLE
openwrt v19.07.2 源码整合luci后 web界面没有smartdns

### ISSUE THREAD

**Issue by openips** [pymumu/luci-app-smartdns#19]
如题 luci-app-smartdns更新日期0415

**Comment by openips** [comment]
![03](https://user-images.githubusercontent.com/47168453/79322440-6b6a0980-7f3f-11ea-85e5-236f36daece6.jpg)
![01](https://user-images.githubusercontent.com/47168453/79322467-7329ae00-7f3f-11ea-8b3b-e9ec463d2ce8.jpg)
![02](https://user-images.githubusercontent.com/47168453/79322472-745adb00-7f3f-11ea-9e73-f3e0da6ab8ed.jpg)

**Comment by thisdk** [comment]
对..我也有这样的问题..我之前无法编译.后面改了一下脚本,放到pageck目录下可以.但是编译完了.在菜单无法看到

**Comment by xxp2277** [comment]
> 
> 
> 对..我也有这样的问题..我之前无法编译.后面改了一下脚本,放到pageck目录下可以.但是编译完了.在菜单无法看到

怎么改的脚本？

**Comment by thisdk** [comment]
> > 对..我也有这样的问题..我之前无法编译.后面改了一下脚本,放到pageck目录下可以.但是编译完了.在菜单无法看到
> 
> 怎么改的脚本？

你可以进我个人主页看那个我fork的项目.有一个提交

**Comment by sarsmark-git** [comment]
我也是这样，编译完成后，找不到smartdns

**Comment by pymumu** [comment]
用compat版本，master分支是最新的javascript版本

**Comment by openips** [comment]
怎么用啊 有地址没

**Comment by pymumu** [comment]
readme的最后有个懒人脚本
分支改成lede
懒人脚本运行前要执行scripts/feed luci update

**Comment by openips** [comment]
成功了 谢谢 等script修复了再试试
