### ISSUE TITLE
官方源1907下，在make menuconfig后的luci选项下找不到luci-app-smartdns选项

### ISSUE THREAD

**Issue by Zack0617** [pymumu/luci-app-smartdns#4]
如题目

**Comment by RealKiro** [comment]
> 如题目

![image](https://user-images.githubusercontent.com/33367701/70959925-778caa00-20b8-11ea-916d-98537f23c4d7.png)
makefile改一下

**Comment by zxlhhyccc** [comment]
没有问题。。。。

**Comment by L-vivi** [comment]
同样问题，我是放在package目录下的，确实找不到

**Comment by Zack0617** [comment]
@zxlhhyccc  请教一下你具体怎么编译的，下载的源码放哪个目录，谢谢.

**Comment by laincat** [comment]
我也找不到。。。奇怪了都。

**Comment by laincat** [comment]
原来是因为这个。。。。

```
Makefile:24: ../../luci.mk: No such file or directory
make[2]: *** No rule to make target '../../luci.mk'.  Stop.
```

**Comment by saoba1982** [comment]
我也一样，该如何解决呢？

**Comment by Zack0617** [comment]
@laincat  请问你找到解决方案了吗？

**Comment by pymumu** [comment]
正将smartdns推送的openwrt软件仓库，稍安勿躁。

https://github.com/openwrt/packages/pull/10797

**Comment by simonsmh** [comment]
请参考这个pr
https://github.com/pymumu/luci-app-smartdns/pull/2

**Comment by Zack0617** [comment]
.
