### ISSUE TITLE
请问开发者luci下面新加入的“下载文件设置”及“下载文件”应该如何使用

### ISSUE THREAD

**Issue by gforce1206** [pymumu/luci-app-smartdns#44]
RT，运行环境是lede，我在“下载文件”处，进行了如下设置，URL为域名黑白名单的下载地址，配合不同的服务组使用，点击保存后好像不起作用，查看/etc/smartdns下没有domain-set文件夹，请问应该如何设置才正确呢？
![下载文件](https://user-images.githubusercontent.com/72802453/211001011-fb0913ec-ad47-477d-9c37-e96623719fc6.PNG)

**Comment by pymumu** [comment]
https://github.com/pymumu/smartdns/releases/tag/feature-dns-forwarding

**Comment by gforce1206** [comment]
> https://github.com/pymumu/smartdns/releases/tag/feature-dns-forwarding

thanks

**Comment by jaydiao521** [comment]
你设置好了吗？我新建了这两个文件夹，设置后点更新文件，文件夹是空的。手动放进去也不起作用。

**Comment by gforce1206** [comment]
> 你设置好了吗？我新建了这两个文件夹，设置后点更新文件，文件夹是空的。手动放进去也不起作用。

luci和smartdns都要更新到40，你smartdns应该还是38.1
